/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExpenseTrackerDebtCreditNameTagsPersonUser } from "./ExpenseTrackerDebtCreditNameTagsPersonUser";
import { ExpenseTrackerDebtCreditNameTagsPersonUserCountArgs } from "./ExpenseTrackerDebtCreditNameTagsPersonUserCountArgs";
import { ExpenseTrackerDebtCreditNameTagsPersonUserFindManyArgs } from "./ExpenseTrackerDebtCreditNameTagsPersonUserFindManyArgs";
import { ExpenseTrackerDebtCreditNameTagsPersonUserFindUniqueArgs } from "./ExpenseTrackerDebtCreditNameTagsPersonUserFindUniqueArgs";
import { DeleteExpenseTrackerDebtCreditNameTagsPersonUserArgs } from "./DeleteExpenseTrackerDebtCreditNameTagsPersonUserArgs";
import { ExpenseTrackerDebtCreditNameTagsPersonUserService } from "../expenseTrackerDebtCreditNameTagsPersonUser.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ExpenseTrackerDebtCreditNameTagsPersonUser)
export class ExpenseTrackerDebtCreditNameTagsPersonUserResolverBase {
  constructor(
    protected readonly service: ExpenseTrackerDebtCreditNameTagsPersonUserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ExpenseTrackerDebtCreditNameTagsPersonUser",
    action: "read",
    possession: "any",
  })
  async _expenseTrackerDebtCreditNameTagsPersonUsersMeta(
    @graphql.Args() args: ExpenseTrackerDebtCreditNameTagsPersonUserCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ExpenseTrackerDebtCreditNameTagsPersonUser])
  @nestAccessControl.UseRoles({
    resource: "ExpenseTrackerDebtCreditNameTagsPersonUser",
    action: "read",
    possession: "any",
  })
  async expenseTrackerDebtCreditNameTagsPersonUsers(
    @graphql.Args() args: ExpenseTrackerDebtCreditNameTagsPersonUserFindManyArgs
  ): Promise<ExpenseTrackerDebtCreditNameTagsPersonUser[]> {
    return this.service.expenseTrackerDebtCreditNameTagsPersonUsers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ExpenseTrackerDebtCreditNameTagsPersonUser, {
    nullable: true,
  })
  @nestAccessControl.UseRoles({
    resource: "ExpenseTrackerDebtCreditNameTagsPersonUser",
    action: "read",
    possession: "own",
  })
  async expenseTrackerDebtCreditNameTagsPersonUser(
    @graphql.Args()
    args: ExpenseTrackerDebtCreditNameTagsPersonUserFindUniqueArgs
  ): Promise<ExpenseTrackerDebtCreditNameTagsPersonUser | null> {
    const result =
      await this.service.expenseTrackerDebtCreditNameTagsPersonUser(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ExpenseTrackerDebtCreditNameTagsPersonUser)
  @nestAccessControl.UseRoles({
    resource: "ExpenseTrackerDebtCreditNameTagsPersonUser",
    action: "delete",
    possession: "any",
  })
  async deleteExpenseTrackerDebtCreditNameTagsPersonUser(
    @graphql.Args() args: DeleteExpenseTrackerDebtCreditNameTagsPersonUserArgs
  ): Promise<ExpenseTrackerDebtCreditNameTagsPersonUser | null> {
    try {
      return await this.service.deleteExpenseTrackerDebtCreditNameTagsPersonUser(
        args
      );
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
