/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ExpenseTrackerDebtCreditNameTagsPersonUserService } from "../expenseTrackerDebtCreditNameTagsPersonUser.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExpenseTrackerDebtCreditNameTagsPersonUserCreateInput } from "./ExpenseTrackerDebtCreditNameTagsPersonUserCreateInput";
import { ExpenseTrackerDebtCreditNameTagsPersonUser } from "./ExpenseTrackerDebtCreditNameTagsPersonUser";
import { ExpenseTrackerDebtCreditNameTagsPersonUserFindManyArgs } from "./ExpenseTrackerDebtCreditNameTagsPersonUserFindManyArgs";
import { ExpenseTrackerDebtCreditNameTagsPersonUserWhereUniqueInput } from "./ExpenseTrackerDebtCreditNameTagsPersonUserWhereUniqueInput";
import { ExpenseTrackerDebtCreditNameTagsPersonUserUpdateInput } from "./ExpenseTrackerDebtCreditNameTagsPersonUserUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ExpenseTrackerDebtCreditNameTagsPersonUserControllerBase {
  constructor(
    protected readonly service: ExpenseTrackerDebtCreditNameTagsPersonUserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({
    type: ExpenseTrackerDebtCreditNameTagsPersonUser,
  })
  @nestAccessControl.UseRoles({
    resource: "ExpenseTrackerDebtCreditNameTagsPersonUser",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createExpenseTrackerDebtCreditNameTagsPersonUser(
    @common.Body() data: ExpenseTrackerDebtCreditNameTagsPersonUserCreateInput
  ): Promise<ExpenseTrackerDebtCreditNameTagsPersonUser> {
    return await this.service.createExpenseTrackerDebtCreditNameTagsPersonUser({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ExpenseTrackerDebtCreditNameTagsPersonUser] })
  @ApiNestedQuery(ExpenseTrackerDebtCreditNameTagsPersonUserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ExpenseTrackerDebtCreditNameTagsPersonUser",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async expenseTrackerDebtCreditNameTagsPersonUsers(
    @common.Req() request: Request
  ): Promise<ExpenseTrackerDebtCreditNameTagsPersonUser[]> {
    const args = plainToClass(
      ExpenseTrackerDebtCreditNameTagsPersonUserFindManyArgs,
      request.query
    );
    return this.service.expenseTrackerDebtCreditNameTagsPersonUsers({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ExpenseTrackerDebtCreditNameTagsPersonUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExpenseTrackerDebtCreditNameTagsPersonUser",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async expenseTrackerDebtCreditNameTagsPersonUser(
    @common.Param()
    params: ExpenseTrackerDebtCreditNameTagsPersonUserWhereUniqueInput
  ): Promise<ExpenseTrackerDebtCreditNameTagsPersonUser | null> {
    const result =
      await this.service.expenseTrackerDebtCreditNameTagsPersonUser({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ExpenseTrackerDebtCreditNameTagsPersonUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExpenseTrackerDebtCreditNameTagsPersonUser",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateExpenseTrackerDebtCreditNameTagsPersonUser(
    @common.Param()
    params: ExpenseTrackerDebtCreditNameTagsPersonUserWhereUniqueInput,
    @common.Body() data: ExpenseTrackerDebtCreditNameTagsPersonUserUpdateInput
  ): Promise<ExpenseTrackerDebtCreditNameTagsPersonUser | null> {
    try {
      return await this.service.updateExpenseTrackerDebtCreditNameTagsPersonUser(
        {
          where: params,
          data: data,
          select: {
            id: true,
            createdAt: true,
            updatedAt: true,
          },
        }
      );
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ExpenseTrackerDebtCreditNameTagsPersonUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExpenseTrackerDebtCreditNameTagsPersonUser",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteExpenseTrackerDebtCreditNameTagsPersonUser(
    @common.Param()
    params: ExpenseTrackerDebtCreditNameTagsPersonUserWhereUniqueInput
  ): Promise<ExpenseTrackerDebtCreditNameTagsPersonUser | null> {
    try {
      return await this.service.deleteExpenseTrackerDebtCreditNameTagsPersonUser(
        {
          where: params,
          select: {
            id: true,
            createdAt: true,
            updatedAt: true,
          },
        }
      );
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
